//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.16 at 04:15:25 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thomas-bayer.com/blz/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.saib.consumer.stub;
